In [1]:
NAME = "Yin Qiu"

---

# Lab 6: Skip Gram

**Please read the following instructions very carefully**

## Working on the assignment / FAQs
- **Always use the seed/random_state as *42* wherever applicable** (This is to ensure repeatability in answers, across students and coding environments) 
- The type of question and the points they carry are indicated in each question cell
- To avoid any ambiguity, each question also specifies what *value* must be set. Note that these are dummy values and not the answers
- If an autograded question has multiple answers (due to differences in handling NaNs, zeros etc.), all answers will be considered.
- You can delete the `raise NotImplementedError()`
- **Submitting the assignment** : Download the '.ipynb' file from Colab and upload it to bcourses. Do not delete any outputs from cells before submitting.
- That's about it. Happy coding!


Available software:
 - Python's Gensim module: https://radimrehurek.com/gensim/ (install using pip)
 - Sklearn’s  TSNE module in case you use TSNE to reduce dimension (optional)
 - Python’s Matplotlib (optional)

_Note: The most important hyper parameters of skip-gram/CBOW are vector size and windows size_


In [2]:
!pip install gensim
!wget -nc https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz 


import pandas as pd
import numpy as np 
import gensim



--2020-10-27 16:52:58--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.169.29
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.169.29|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/x-gzip]
Saving to: ‘GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G  16.5MB/s    in 2m 7s   

2020-10-27 16:55:05 (12.4 MB/s) - ‘GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]



### **Q1 (1 point)** 
Find the cosine similarity between the following word pairs

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)

In [3]:
from gensim.models import KeyedVectors

model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary=True)

In [4]:
word_pairs = [('France', 'England'),
              ('smaller', 'bigger'),
              ('England', 'London'),
              ('France', 'Rocket'),
              ('big', 'bigger')]
similarities = []
for pair in word_pairs:
  similarities.append(model.similarity(pair[0], pair[1]))
print(similarities)

[0.39804944, 0.7302272, 0.43992856, 0.07114174, 0.68423855]


/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [5]:
#Replace 0 with the code / value; Do not delete this cell
similarity_pair1 = similarities[0]
similarity_pair2 = similarities[1]
similarity_pair3 = similarities[2]
similarity_pair4 = similarities[3]
similarity_pair5 = similarities[4]



In [6]:
#This is an autograded cell, do not edit/delete
print(similarity_pair1, similarity_pair2, similarity_pair3, similarity_pair4, similarity_pair5)

0.39804944 0.7302272 0.43992856 0.07114174 0.68423855


### **Q2 (1 point)** 
Write an expression to extract the vector representations of the words: 

- France
- England
- smaller
- bigger
- rocket
- big

Get only the first 5 elements for each vector representation.

In [7]:
word_vectors = model.wv
lst_words = ['France', 'England', 'smaller', 'bigger', 'rocket', 'big']
wordrep_5 = []
for word in lst_words:
  wordrep_5.append(word_vectors[word][:5])
print(wordrep_5)

[array([0.04858398, 0.07861328, 0.32421875, 0.03491211, 0.07714844],
      dtype=float32), array([-0.19824219,  0.11523438,  0.0625    , -0.05834961,  0.2265625 ],
      dtype=float32), array([-0.05004883,  0.03417969, -0.0703125 ,  0.17578125,  0.00689697],
      dtype=float32), array([-0.06542969, -0.09521484, -0.06225586,  0.16210938,  0.01989746],
      dtype=float32), array([-0.03198242,  0.27148438, -0.2890625 , -0.15429688,  0.16894531],
      dtype=float32), array([ 0.11132812,  0.10595703, -0.07373047,  0.18847656,  0.07666016],
      dtype=float32)]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


In [8]:
#Replace 0 with the code / value to get the first 5 elements of each vector; Do not delete this cell
vector_1 = wordrep_5[0]
vector_2 = wordrep_5[1]
vector_3 = wordrep_5[2]
vector_4 = wordrep_5[3]
vector_5 = wordrep_5[4]
vector_6 = wordrep_5[5]



In [9]:
#This is an autograded cell, do not edit/delete
print(vector_1)
print(vector_2)
print(vector_3)
print(vector_4)
print(vector_5)
print(vector_6)


[0.04858398 0.07861328 0.32421875 0.03491211 0.07714844]
[-0.19824219  0.11523438  0.0625     -0.05834961  0.2265625 ]
[-0.05004883  0.03417969 -0.0703125   0.17578125  0.00689697]
[-0.06542969 -0.09521484 -0.06225586  0.16210938  0.01989746]
[-0.03198242  0.27148438 -0.2890625  -0.15429688  0.16894531]
[ 0.11132812  0.10595703 -0.07373047  0.18847656  0.07666016]


### **Q3 (1 point)** 
Find the euclidean distances between the word pairs : 

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)


In [10]:
def euclidean_dist(pair):
  a = pair[0]
  b = pair[1]
  d = word_vectors[a] - word_vectors[b]
  return np.linalg.norm(d)

word_pairs = [('France', 'England'),
              ('smaller', 'bigger'),
              ('England', 'London'),
              ('France', 'Rocket'),
              ('big', 'bigger')]
eu_dists = []
for pair in word_pairs:
  eu_dists.append(euclidean_dist(pair))

print(eu_dists)


[3.0151067, 1.8618743, 2.8752837, 3.892071, 1.9586496]


In [11]:
#Replace 0 with the code / value; Do not delete this cell
eu_dist1 = eu_dists[0]
eu_dist2 = eu_dists[1]
eu_dist3 = eu_dists[2]
eu_dist4 = eu_dists[3]
eu_dist5 = eu_dists[4]



In [12]:
#This is an autograded cell, do not edit / delete
print(eu_dist1)
print(eu_dist2)
print(eu_dist3)
print(eu_dist4)
print(eu_dist5)


3.0151067
1.8618743
2.8752837
3.892071
1.9586496


### **Q4 (1 point)**
Time to dabble with the power of Word2Vec. Find the 2 closest words  for the following conditions:  
- (King - Man + Queen)
- (bigger - big + small)
- (man + programmer - woman)
- (waiting - wait + run)
- (Texas + Milwaukee – Wisconsin)

In [13]:
def mostsimilar2(positive, negative):
  return model.most_similar(positive=positive, negative=negative, topn=2)

closest1 = mostsimilar2(['King', 'Queen'], ['Man'])
closest2 = mostsimilar2(['bigger', 'small'], ['big'])
closest3 = mostsimilar2(['man', 'programmer'], ['woman'])
closest4 = mostsimilar2(['waiting', 'run'], ['wait'])
closest5 = mostsimilar2(['Texas', 'Milwaukee'], ['Wisconsin'])

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [14]:
#Replace 0 with the code / value; Do not delete this cell
closest1 = closest1
closest2 = closest2
closest3 = closest3
closest4 = closest4
closest5 = closest5



In [15]:
#This is an autograded cell, do not edit/delete
print(closest1)
print(closest2)
print(closest3)
print(closest4)
print(closest5)


[('Queen_Elizabeth', 0.5257916450500488), ('monarch', 0.5004087090492249)]
[('larger', 0.7402471899986267), ('smaller', 0.732999324798584)]
[('programer', 0.5371963977813721), ('programmers', 0.5310999155044556)]
[('running', 0.5654535889625549), ('runs', 0.49640005826950073)]
[('Houston', 0.7767744064331055), ('Fort_Worth', 0.7270511388778687)]


### **Q5 (3 points)**
Using the vectors for the words in the Google News dataset, explore the semantic representation of these words through K-means clustering and explain your findings.

*Note : Since there are ~3Mil words in the vocabulary, you can downsample it to ~20-30k randomly selected words*

**Do not delete the below cell**

In [16]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [17]:
# parse the words to a list, and randomly select 30k of them for clustering
keys = word_vectors.index2entity
keys = np.random.choice(a=keys, size=30000, replace=False) # randomly select 30000 unique words from the 3 mil words
keys.shape

(30000,)

In [18]:
# use the downsized word vectors to train the kmeans model
new_wv = word_vectors[keys]

# iterate from 2 to 10 to find best k
K = range(2,11)
scores = []
for k in K:
  kmeans = KMeans(n_clusters=k, random_state=42)
  kmeans.fit(new_wv)
  score = silhouette_score(new_wv, kmeans.labels_) # use silhouette score as metric, higher the better
  scores.append(score)

max_index = scores.index(max(scores))
best_k = max_index+2
print(best_k)

2


In [19]:
# run the kmeans again with the best k of 2
kmeans_best = KMeans(n_clusters=best_k, random_state=42)
kmeans_best.fit(new_wv)
labels = kmeans_best.labels_
centers = kmeans_best.cluster_centers_
centers.shape

(2, 300)

In [23]:
# silhouette score
silhouette_score(new_wv, kmeans_best.labels_)

0.21829157

**The silhouette score is supposed to be in -1 to 1. The larger the better. The score for kmeans model when k=2 is only 0.22, which tell us the ratio of intra-cluster distances to inter-cluster distances is about 1/5. It's not very good but still acceptable.**

In [20]:
# number of words assigned to each cluster
(cluster, counts) = np.unique(kmeans_best.labels_, return_counts=True)
print(dict(zip(cluster, counts)))

{0: 6500, 1: 23500}


**It appears the majority of words were assigned to cluster 2. For such a big data set and a very small k=2, the imbalanced assignment to cluters may tell us this clustering is not very meaningful. We will check further below.**

In [21]:
# find the 10 most similar words by vector to centroids in cluster 1 and cluster 2
close_clu1 = model.similar_by_vector(vector=centers[0], topn=10)
close_clu2 = model.similar_by_vector(vector=centers[1], topn=10)

# print the 10 similar words in each cluster and respective cosine similarity
for word in close_clu1:
  print(word)
print('\n')
for word in close_clu2:
  print(word)

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


('Emil_Protalinski_Published', 0.9234708547592163)
('By_HuDie_####-##-##', 0.9210418462753296)
('BY_GEOFF_KOHL', 0.9189164638519287)
('By_QianMian_####-##-##', 0.9186978936195374)
('By_XiaoBing_####-##-##', 0.9161226749420166)
('BY_DANNY_GALLAGHER', 0.9147441387176514)
('STACY_LEE', 0.9140746593475342)
('By_Riva_Froymovich', 0.9123396873474121)
('REYNOLDS_GALLERY', 0.9099236130714417)
('FOOD_OOH_IT', 0.9098910689353943)


('http_dol##.net_index###.html_http', 0.914204478263855)
('dol##.net_index####.html_http_dol##.net', 0.9038791656494141)
('index###.html_http_dol##.net_index###.html', 0.9032235145568848)
('Deltagen_undertakes', 0.9029473662376404)
('By_TRICIA_SCRUGGS', 0.8984065055847168)
('BY_STEFANIE_WHITE', 0.8975433707237244)
('Manufacturing_bioplastics', 0.8972487449645996)
('PRESCRIPTION_DRUGS_Gradually', 0.8947985768318176)
('EXCO_undertakes', 0.8935084342956543)
('under_CorMedix_collaborations', 0.8930904865264893)


**I found the best k for k-means clustering is 2, using silhouette score. With each of the 2 clusters, I printed the the 10 most similar vectors to the centroid. There is no clear pattern to me in each cluster. I can hypothetically think that the words in the first cluster are relevant to http address and corporate name, and the words in the second cluster are relevant to personal signature and publication series code. However, this is just a hypothesis and needs to be confirmed with further exploration.**

### **Q6 (1 point)**
What loss function does the skipgram model use and briefly describe what this function is minimizing.

**Do not delete the below cell**

**The loss function for skip-gram algorithm is corss entropy， which is used to measure the negative sum of the predicted probability distribution of the output of softmax. When the output of softmax y_j is close to 1 then log(y_j) in C is close to 0; when y_j is less than 1, -log(y_j) will be larger than 1, making the loss function C larger. We would like to minimize the divergence of predicted probability distribution, so that it will be close to the "target" probability distribution (t_j), where the correct class is 1 and everything else is 0. We have t_j times the log(y_j) to keep only the correct class. So minimizing C towards 0 means we have higher predicted probability to the correct output words.**

### **Bonus Question (1 point)** 
Find at least 2 interesting word vec combinations like the ones given in Q4

**Do not delete the below cell**

In [24]:
funwordpair1 = mostsimilar2(['happy','joy'], ['sad'])
print(funwordpair1)

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('sheer_joy', 0.5615313053131104), ('delight', 0.5426716208457947)]


In [43]:
funwordpair2 = mostsimilar2(['California', 'Hollywood'], ['tech'])
print(funwordpair2)

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('Southern_California', 0.600623369216919), ('Los_Angeles', 0.5748981237411499)]
